In [20]:
import pandas as pd

In [21]:
# read csv file 
food = pd.read_csv("../data/raw/global_food_prices.csv")
inflation = pd.read_csv("../data/raw/inflation.csv", skiprows=4) # That 4 rows is just uptodate informations.

/var/folders/0f/9fk_2m_j5y9618mjy6yhmtr40000gn/T/ipykernel_68663/317041543.py:2: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  food = pd.read_csv("../data/raw/global_food_prices.csv")

In [22]:
# check the first 5 rows.
food.head()

,adm0_id,adm0_name,adm1_id,adm1_name,mkt_id,mkt_name,cm_id,cm_name,cur_id,cur_name,pt_id,pt_name,um_id,um_name,mp_month,mp_year,mp_price,mp_commoditysource
0,1.0,Afghanistan,272,Badakhshan,266,Fayzabad,55,Bread - Retail,0.0,AFN,15,Retail,5,KG,1,2014,50.0,NaN
1,1.0,Afghanistan,272,Badakhshan,266,Fayzabad,55,Bread - Retail,0.0,AFN,15,Retail,5,KG,2,2014,50.0,NaN
2,1.0,Afghanistan,272,Badakhshan,266,Fayzabad,55,Bread - Retail,0.0,AFN,15,Retail,5,KG,3,2014,50.0,NaN
3,1.0,Afghanistan,272,Badakhshan,266,Fayzabad,55,Bread - Retail,0.0,AFN,15,Retail,5,KG,4,2014,50.0,NaN
4,1.0,Afghanistan,272,Badakhshan,266,Fayzabad,55,Bread - Retail,0.0,AFN,15,Retail,5,KG,5,2014,50.0,NaN

In [23]:
inflation.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
0,Aruba,ABW,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,-1.028282,3.626041,4.257462,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Africa Eastern and Southern,AFE,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,6.221375,4.689806,4.102851,5.191629,6.824727,10.883478,7.399186,4.770857,NaN,NaN
2,Afghanistan,AFG,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,4.975952,0.626149,2.302373,5.601888,5.133203,13.712102,-4.644709,-6.601186,NaN,NaN
3,Africa Western and Central,AFW,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,1.725486,1.784050,1.983092,2.490378,3.745568,7.949251,5.221168,3.608044,NaN,NaN
4,Angola,AGO,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,29.844480,19.628938,17.080954,22.271539,25.754295,21.355290,13.644102,28.240495,NaN,NaN

In [24]:
# check food datatype
food.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2050638 entries, 0 to 2050637
Data columns (total 18 columns):
 #   Column              Dtype
---  ------              -----
 0   adm0_id             float64
 1   adm0_name           object
 2   adm1_id             int64
 3   adm1_name           object
 4   mkt_id              int64
 5   mkt_name            object
 6   cm_id               int64
 7   cm_name             object
 8   cur_id              float64
 9   cur_name            object
 10  pt_id               int64
 11  pt_name             object
 12  um_id               int64
 13  um_name             object
 14  mp_month            int64
 15  mp_year             int64
 16  mp_price            float64
 17  mp_commoditysource  float64
dtypes: float64(4), int64(7), object(7)
memory usage: 281.6+ MB

In [25]:
# select only the row that we want eg. country,product,price,month,year,unit
food_clean = food[['adm0_name', 'cm_name', 'mp_price', 'mp_month', 'mp_year', 'um_name']]

In [26]:
# rename to common name
food_clean = food_clean.rename(columns = {
    'adm0_name' : 'country',
    'cm_name' : 'product',
    'mp_price' : 'price', 
    'mp_month' : 'month', 
    'mp_year' : 'year', 
    'um_name' : 'unit'
})

In [27]:
# clean food data
food_clean

             country                  product      price  month  year    unit
0        Afghanistan           Bread - Retail    50.0000      1  2014      KG
1        Afghanistan           Bread - Retail    50.0000      2  2014      KG
2        Afghanistan           Bread - Retail    50.0000      3  2014      KG
3        Afghanistan           Bread - Retail    50.0000      4  2014      KG
4        Afghanistan           Bread - Retail    50.0000      5  2014      KG
...              ...                      ...        ...    ...   ...     ...
2050633     Zimbabwe   Beans (sugar) - Retail   233.3333      6  2021      KG
2050634     Zimbabwe      Toothpaste - Retail   112.5000      6  2021  100 ML
2050635     Zimbabwe    Laundry soap - Retail   114.0000      6  2021      KG
2050636     Zimbabwe   Handwash soap - Retail    59.5000      6  2021   250 G
2050637     Zimbabwe  Fish (kapenta) - Retail  1200.0000      6  2021      KG

[2050638 rows x 6 columns]

In [28]:
# check infaltion datatype
inflation.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 0 to 265
Data columns (total 71 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    266 non-null    object
 1   Country Code    266 non-null    object
 2   Indicator Name  266 non-null    object
 3   Indicator Code  266 non-null    object
 4   1960            63 non-null     float64
 5   1961            65 non-null     float64
 6   1962            67 non-null     float64
 7   1963            67 non-null     float64
 8   1964            72 non-null     float64
 9   1965            76 non-null     float64
 10  1966            82 non-null     float64
 11  1967            87 non-null     float64
 12  1968            88 non-null     float64
 13  1969            89 non-null     float64
 14  1970            92 non-null     float64
 15  1971            95 non-null     float64
 16  1972            97 non-null     float64
 17  1973            99 non-null     float64
 18  1974            101 non-null    float64
 19  1975            103 non-null    float64
 20  1976            104 non-null    float64
 21  1977            106 non-null    float64
 22  1978            106 non-null    float64
 23  1979            104 non-null    float64
 24  1980            107 non-null    float64
 25  1981            116 non-null    float64
 26  1982            117 non-null    float64
 27  1983            117 non-null    float64
 28  1984            120 non-null    float64
 29  1985            121 non-null    float64
 30  1986            127 non-null    float64
 31  1987            130 non-null    float64
 32  1988            130 non-null    float64
 33  1989            133 non-null    float64
 34  1990            133 non-null    float64
 35  1991            137 non-null    float64
 36  1992            144 non-null    float64
 37  1993            150 non-null    float64
 38  1994            153 non-null    float64
 39  1995            157 non-null    float64
 40  1996            160 non-null    float64
 41  1997            160 non-null    float64
 42  1998            160 non-null    float64
 43  1999            162 non-null    float64
 44  2000            165 non-null    float64
 45  2001            170 non-null    float64
 46  2002            172 non-null    float64
 47  2003            175 non-null    float64
 48  2004            176 non-null    float64
 49  2005            179 non-null    float64
 50  2006            182 non-null    float64
 51  2007            184 non-null    float64
 52  2008            185 non-null    float64
 53  2009            188 non-null    float64
 54  2010            190 non-null    float64
 55  2011            194 non-null    float64
 56  2012            193 non-null    float64
 57  2013            192 non-null    float64
 58  2014            192 non-null    float64
 59  2015            191 non-null    float64
 60  2016            191 non-null    float64
 61  2017            186 non-null    float64
 62  2018            185 non-null    float64
 63  2019            185 non-null    float64
 64  2020            180 non-null    float64
 65  2021            180 non-null    float64
 66  2022            180 non-null    float64
 67  2023            178 non-null    float64
 68  2024            176 non-null    float64
 69  2025            0 non-null      float64
 70  Unnamed: 70     0 non-null      float64
dtypes: float64(67), object(4)
memory usage: 147.7+ KB

In [29]:
# drop the column that we don't need
inflation_clean = inflation.drop(columns = ['Country Code','Indicator Name','Indicator Code','Unnamed: 70'])

In [30]:
inflation_clean

,Country Name,1960,1961,1962,1963,1964,1965,1966,1967,1968,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,Aruba,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.931196,-1.028282,3.626041,4.257462,NaN,NaN,NaN,NaN,NaN,NaN
1,Africa Eastern and Southern,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.446877,6.221375,4.689806,4.102851,5.191629,6.824727,10.883478,7.399186,4.770857,NaN
2,Afghanistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.383892,4.975952,0.626149,2.302373,5.601888,5.133203,13.712102,-4.644709,-6.601186,NaN
3,Africa Western and Central,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.487416,1.725486,1.784050,1.983092,2.490378,3.745568,7.949251,5.221168,3.608044,NaN
4,Angola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,30.694415,29.844480,19.628938,17.080954,22.271539,25.754295,21.355290,13.644102,28.240495,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.273169,1.488234,1.053798,2.675992,0.198228,3.353691,11.580510,4.944324,1.619450,NaN
262,"Yemen, Rep.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
263,South Africa,1.288877,2.102351,1.246275,1.337971,2.534989,4.069019,3.489237,3.538966,1.986134,...,6.602908,5.186187,4.509873,4.102851,3.232388,4.618745,7.039873,6.075244,4.361152,NaN
264,Zambia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,17.869730,6.577312,7.494572,9.150316,15.733060,22.020768,10.993204,10.884532,14.985626,NaN
265,Zimbabwe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-1.543670,0.893962,10.618866,255.304991,557.201817,98.546105,104.705171,NaN,NaN,NaN

In [31]:
# change from wide format to long format (unpivot) column -> row ; 
# (pivot) row -> column
inflation_clean = inflation_clean.melt(
    id_vars=['Country Name'], # keep this
    var_name='year', # new column name
    value_name='inflation_rate' # new value name
)

In [32]:
# rename columns country
inflation_clean = inflation_clean.rename(columns = {
    'Country Name': 'country'
})

In [19]:
inflation_clean

                      Country Name  year  inflation_rae
0                            Aruba  1960            NaN
1      Africa Eastern and Southern  1960            NaN
2                      Afghanistan  1960            NaN
3       Africa Western and Central  1960            NaN
4                           Angola  1960            NaN
...                            ...   ...            ...
17551                       Kosovo  2025            NaN
17552                  Yemen, Rep.  2025            NaN
17553                 South Africa  2025            NaN
17554                       Zambia  2025            NaN
17555                     Zimbabwe  2025            NaN

[17556 rows x 3 columns]

In [ ]:
# change year to int type
inflation_clean['year'] = inflation_clean['year'].astype(int)

In [40]:
# drop all na in inflation_rate
inflation_clean = inflation_clean.dropna(subset=['inflation_rate'])

In [43]:
inflation_clean

            country  year  inflation_rate
13        Australia  1960        3.728822
14          Austria  1960        1.945749
17          Belgium  1960        0.299467
19     Burkina Faso  1960        7.788162
28          Bolivia  1960       11.533153
...             ...   ...             ...
17281      Viet Nam  2024        3.621093
17284         Samoa  2024        2.172455
17285        Kosovo  2024        1.619450
17287  South Africa  2024        4.361152
17288        Zambia  2024       14.985626

[9066 rows x 3 columns]

In [ ]:
# merge using inner join
food_inflation = pd.merge(
    food_clean, # Always!!! use the one with most data
    inflation_clean,
    on=['country', 'year'],
    how='inner'
)

In [42]:
food_inflation

,country,product,price,month,year,unit,inflation_rate
0,Afghanistan,Bread - Retail,50.0000,1,2014,KG,4.673996
1,Afghanistan,Bread - Retail,50.0000,2,2014,KG,4.673996
2,Afghanistan,Bread - Retail,50.0000,3,2014,KG,4.673996
3,Afghanistan,Bread - Retail,50.0000,4,2014,KG,4.673996
4,Afghanistan,Bread - Retail,50.0000,5,2014,KG,4.673996
...,...,...,...,...,...,...,...
1495538,Zimbabwe,Beans (sugar) - Retail,233.3333,6,2021,KG,98.546105
1495539,Zimbabwe,Toothpaste - Retail,112.5000,6,2021,100 ML,98.546105
1495540,Zimbabwe,Laundry soap - Retail,114.0000,6,2021,KG,98.546105
1495541,Zimbabwe,Handwash soap - Retail,59.5000,6,2021,250 G,98.546105
1495542,Zimbabwe,Fish (kapenta) - Retail,1200.0000,6,2021,KG,98.546105

In [ ]:
# check how many country are there
food_inflation['country'].unique()

array(['Afghanistan', 'Algeria', 'Angola', 'Argentina', 'Armenia',
       'Azerbaijan', 'Bangladesh', 'Belarus', 'Benin', 'Bhutan',
       'Bolivia', 'Burkina Faso', 'Burundi', 'Cambodia', 'Cameroon',
       'Central African Republic', 'Chad', 'China', 'Colombia',
       'Costa Rica', "Cote d'Ivoire", 'Djibouti', 'Dominican Republic',
       'Ecuador', 'El Salvador', 'Ethiopia', 'Gabon', 'Georgia', 'Ghana',
       'Guatemala', 'Guinea', 'Guinea-Bissau', 'Haiti', 'Honduras',
       'Indonesia', 'Iraq', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya',
       'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Madagascar', 'Malawi',
       'Mali', 'Mauritania', 'Mexico', 'Mongolia', 'Mozambique',
       'Myanmar', 'Namibia', 'Nepal', 'Nicaragua', 'Niger', 'Nigeria',
       'Pakistan', 'Panama', 'Paraguay', 'Peru', 'Philippines',
       'Russian Federation', 'Rwanda', 'Senegal', 'Sierra Leone',
       'South Africa', 'South Sudan', 'Sri Lanka', 'Sudan',
       'Syrian Arab Republic', 'Tajikistan', 'Thailand', 'Timor-Leste',
       'Togo', 'Uganda', 'Ukraine', 'Viet Nam', 'Zambia', 'Zimbabwe'],
      dtype=object)

In [ ]:
# see what product we have
food_inflation['product'].unique()

array(['Bread - Retail', 'Wheat - Retail', 'Rice (low quality) - Retail',
       'Wage (qualified labour) - Retail', 'Fuel (diesel) - Retail',
       'Exchange rate - Retail',
       'Wage (non-qualified labour, non-agricultural) - Retail',
       'Oil (cooking) - Retail', 'Sugar - Retail', 'Pulses - Retail',
       'Wheat flour (high quality) - Retail', 'Salt - Retail',
       'Rice (high quality) - Retail',
       'Wheat flour (low quality) - Retail', 'Wheat flour - Retail',
       'Rice - Retail', 'Beans (white) - Retail', 'Milk - Retail',
       'Potatoes - Retail', 'Eggs - Retail', 'Meat (chicken) - Retail',
       'Lentils - Retail', 'Pasta - Retail', 'Tomatoes - Retail',
       'Oil - Retail', 'Meat (beef) - Retail', 'Cheese (dry) - Retail',
       'Carrots - Retail', 'Onions - Retail', 'Bananas - Retail',
       'Tea - Retail', 'Fuel (petrol-gasoline) - Retail',
       'Fish (canned) - Retail', 'Apples - Retail', 'Oranges - Retail',
       'Milk (camel) - Retail', 'Meat (camel) - Retail',
       'Tea (sahm) - Retail', 'Oil (palm) - Retail',
       'Cassava flour - Retail', 'Maize flour - Retail',
       'Rice (regular, milled) - Retail', 'Milk (powder) - Retail',
       'Oil (soybean) - Retail', 'Sugar (white) - Retail',
       'Salt (iodised) - Retail', 'Rice (white, imported) - Retail',
       'Maize meal (yellow) - Retail', 'Fish (mackerel, dry) - Retail',
       'Beans (kidney, pinto) - Retail', 'Wheat flour - Wholesale',
       'Wheat - Wholesale', 'Rice (white) - Retail',
       'Maize (yellow) - Wholesale', 'Beans - Retail',
       'Oil (vegetable) - Retail', 'Milk (non-pasteurized) - Retail',
       'Meat (pork) - Retail', 'Peas (split, dry) - Retail',
       'Cabbage - Retail', 'Apples (red) - Retail',
       'Cucumbers (greenhouse) - Retail', 'Tomatoes (paste) - Retail',
       'Beetroots - Retail', 'Fish (fresh) - Retail',
       'Bread (high grade flour) - Retail',
       'Bread (first grade flour) - Retail', 'Buckwheat - Retail',
       'Fuel (kerosene) - Retail', 'Rice (coarse) - Retail',
       'Lentils (masur) - Retail', 'Rice (medium grain) - Wholesale',
       'Rice (medium grain) - Retail',
       'Rice (coarse, BR-8/ 11/, Guti Sharna) - Wholesale',
       'Rice (coarse, BR-8/ 11/, Guti Sharna) - Retail',
       'Rice (coarse, Guti Sharna) - Wholesale',
       'Rice (coarse, Guti Sharna) - Retail', 'Maize - Wholesale',
       'Rice (imported) - Wholesale', 'Rice (imported) - Retail',
       'Sorghum - Wholesale', 'Sorghum - Retail',
       'Maize (white) - Retail', 'Rice (local) - Retail',
       'Millet - Wholesale', 'Millet - Retail', 'Sweet potatoes - Retail',
       'Yam - Retail', 'Plantains - Retail', 'Peas (green, dry) - Retail',
       'Oil (groundnut) - Retail', 'Soybeans - Retail',
       'Sorghum (red) - Retail', 'Cassava (cossette) - Retail',
       'Lemons - Retail', 'Wheat flour (imported) - Retail',
       'Cassava meal (gari) - Retail', 'Fish (tilapia) - Retail',
       'Papaya - Retail', 'Okra (fresh) - Retail',
       'Groundnuts (Bambara) - Retail', 'Peppers (red, dry) - Retail',
       'Groundnuts (small, unshelled) - Retail',
       'Cassava meal (tapioca) - Retail', 'Coconut (dried) - Retail',
       'Yam (white) - Retail', 'Fish (fresh, silvi) - Retail',
       'Oil (palm nut) - Retail', 'Cassava meal (gari, fine) - Retail',
       'Yam (dry) - Retail', 'Yam (flour) - Retail',
       'Beans (red) - Retail', 'Beans (black) - Retail',
       'Rice (paddy) - Retail', 'Cassava (fresh) - Retail',
       'Yam (yellow) - Retail', 'Leafy vegetables - Retail',
       'Maize - Retail', 'Shrimps - Retail', 'Taro - Retail',
       'Snail - Retail', 'Rice (imported, Indian) - Retail',
       'Rice (red) - Retail', 'Meat (beef, chops with bones) - Retail',
       'Meat (chicken, whole) - Retail', 'Noodles (short) - Retail',
       'Potatoes (Irish, imilla) - Retail', 'Rice (estaquilla) - Retail',
       'Bread (wheat) - Retail', 'Meat (chicken, whole) - Wholesale',
       'Potatoes (Irish, imilla) - Wholesale',
       'Rice (carolina 2da) - Retail', 'Potatoes (black) - Retail',
       'Rice (long grain) - Retail', 'Wheat flour (local) - Wholesale',
       'Rice (ordinary, first quality) - Wholesale',
       'Rice (ordinary, second quality) - Wholesale',
       'Wheat flour (imported) - Wholesale', 'Quinoa - Wholesale',
       'Potatoes (Dutch) - Retail', 'Rice (good quality) - Retail',
       'Rice (Grano de Oro) - Retail', 'Rice (carolina, 1st) - Retail',
       'Groundnuts (unshelled) - Retail', 'Beans (niebe) - Retail',
       'Sorghum (white) - Retail', 'Groundnuts (shelled) - Retail',
       'Sorghum (local) - Wholesale', 'Rice - Wholesale',
       'Beans (niebe) - Wholesale', 'Potatoes (Irish) - Retail',
       'Rice (high quality, local) - Retail',
       'Rice (low quality, local) - Retail', 'Meat (goat) - Retail',
       'Avocados - Retail', 'Fish (lates,dry,local) - Retail',
       'Fish (lates,dry,imported) - Retail',
       'Rice (imported, Tanzanian) - Retail',
       'Rice (mixed, low quality) - Wholesale', 'Soybeans - Wholesale',
       'Wage (non-qualified labour) - Retail',
       'Oil (vegetable) - Wholesale',
       'Rice (mixed, low quality) - Retail',
       'Fish (snake head) - Wholesale', 'Fish (snake head) - Retail',
       'Fish (catfish) - Wholesale', 'Fish (catfish) - Retail',
       'Meat (pork, with fat) - Wholesale',
       'Meat (pork, with fat) - Retail', 'Salt (iodised) - Wholesale',
       'Eggplants - Wholesale', 'Eggplants - Retail',
       'Snake gourd - Wholesale', 'Snake gourd - Retail',
       'Cabbage (chinese, flowering) - Wholesale',
       'Cabbage (chinese, flowering) - Retail',
       'Fish (snake head, dry) - Wholesale',
       'Fish (snake head, dry) - Retail', 'Eggs (duck) - Wholesale',
       'Eggs (duck) - Retail', 'Beans (yardlong, green) - Wholesale',
       'Beans (yardlong, green) - Retail', 'Water spinach - Wholesale',
       'Water spinach - Retail', 'Eggs (duck, fermented) - Wholesale',
       'Eggs (duck, fermented) - Retail',
       'Fish (striped catfish) - Wholesale',
       'Fish (striped catfish) - Retail', 'Wax gourd - Wholesale',
       'Wax gourd - Retail', 'Prawn - Wholesale', 'Cassava - Wholesale',
       'Groundnuts (shelled) - Wholesale', 'Fish (dry) - Retail',
       'Oil (cotton) - Retail', 'Onions - Wholesale', 'Chicken - Retail',
       'Rice (long grain, imported) - Retail',
       'Cassava (cossette) - Wholesale', 'Fish (frozen) - Retail',
       'Cocoyam (macabo) - Retail', 'Sesame - Wholesale',
       'Sorghum (red) - Wholesale', 'Cassava - Retail',
       'Maize (yellow) - Retail', 'Cocoyam (macabo) - Wholesale',
       'Rice (local) - Wholesale', 'Groundnuts (unshelled) - Wholesale',
       'Maize (white) - Wholesale', 'Sorghum (white) - Wholesale',
       'Cowpeas (Red) - Wholesale', 'Peas (yellow) - Wholesale',
       'Oil (palm) - Wholesale', 'Beans (red) - Wholesale',
       'Rice (long grain, imported) - Wholesale',
       'Cassava (fresh) - Wholesale', 'Sesame - Retail',
       'Squashes - Retail', 'Fuel (gas) - Retail',
       'Oil (vegetable, imported) - Retail',
       'Meat (chicken, frozen) - Retail',
       'Fish (sardine, canned) - Retail',
       'Rice (broken, imported) - Retail', 'Charcoal - Retail',
       'Water (drinking) - Retail', 'Laundry soap - Retail',
       'Laundry detergent - Retail', 'Pasta (spaghetti) - Retail',
       'Fish - Retail', 'Groundnuts - Retail', 'Fish (smoked) - Retail',
       'Beans (green, fresh) - Retail',
       'Meat (antelope, smoked) - Retail',
       'Meat (gazelle, smoked) - Retail',
       'Livestock (goat, medium-sized castrated male) - Retail',
       'Livestock (cattle) - Retail',
       'Livestock (sheep, medium-sized castrated male) - Retail',
       'Sorghum (berbere) - Retail', 'Peanut - Retail',
       'Rice (Indica) - Wholesale', 'Rice (Japonica) - Wholesale',
       'Wheat flour (first grade) - Wholesale',
       'Maize (local) - Wholesale', 'Potatoes - Wholesale',
       'Meat (chicken) - Wholesale', 'Sugar - Wholesale',
       'Garlic - Wholesale', 'Onions (red) - Wholesale',
       'Onions (white) - Wholesale', 'Pasta - Wholesale',
       'Tomatoes - Wholesale', 'Rice (white) - Wholesale',
       'Meat (pork) - Wholesale', 'Meat (beef) - Wholesale',
       'Potatoes (black) - Wholesale', 'Plantains - Wholesale',
       'Cocoa - Wholesale', 'Coffee - Wholesale', 'Carrots - Wholesale',
       'Cabbage - Wholesale', 'Oil (sunflower) - Wholesale',
       'Salt - Wholesale', 'Rice (paddy) - Wholesale',
       'Chickpeas (imported) - Wholesale', 'Coffee (instant) - Wholesale',
       'Eggs (white, AA) - Wholesale', 'Meat (beef, minced) - Wholesale',
       'Peas (green, dry) - Wholesale', 'Sugar (brown) - Wholesale',
       'Sugar (brown, loaf) - Wholesale', 'Cauliflower - Wholesale',
       'Cucumbers (greenhouse) - Wholesale', 'Milk (powder) - Wholesale',
       'Oranges (big size) - Wholesale',
       'Rice (high quality) - Wholesale', 'Bananas - Wholesale',
       'Beans (red, fresh) - Wholesale', 'Fuel (diesel) - Wholesale',
       'Fuel (petrol-gasoline) - Wholesale', 'Cassava (dry) - Wholesale',
       'Cheese (local) - Wholesale', 'Lemons - Wholesale',
       'Fish (sardine, canned) - Wholesale',
       'Fish (tuna, canned) - Wholesale', 'Onions (local) - Wholesale',
       'Tomatoes (local) - Wholesale', 'Oranges - Wholesale',
       'Beetroots - Wholesale', 'Spinach - Wholesale',
       'Fish (tilapia) - Wholesale', 'Beans (string) - Wholesale',
       'Papaya - Wholesale', 'Blackberry - Wholesale',
       'Broccoli - Wholesale', 'Mangoes - Wholesale',
       'Pumpkin - Wholesale', 'Tomatoes (dried) - Wholesale',
       'Cheese - Wholesale', 'Lentils (imported) - Wholesale',
       'Eggs (local) - Wholesale', 'Peas (fresh) - Wholesale',
       'Milk (pasteurized) - Wholesale', 'Fish (frozen) - Wholesale',
       'Peppers (red) - Wholesale',
       'Meat (chicken, whole, frozen) - Wholesale',
       'Beans (cranberry) - Wholesale', 'Maize flour - Wholesale',
       'Potatoes (unica) - Wholesale', 'Sugar (white) - Wholesale',
       'Beans (green, fresh) - Wholesale', 'Guava - Wholesale',
       'Beans (black, imported) - Wholesale', 'Passion fruit - Wholesale',
       'Yam - Wholesale', 'Fish (dry) - Wholesale',
       'Apples (red) - Wholesale', 'Barley - Wholesale',
       'Beans (black) - Wholesale', 'Rice (milled 80-20) - Wholesale',
       'Rice (denikassia, imported) - Retail', 'Yam (florido) - Retail',
       'Cashew nut - Retail', 'Cornstarch - Retail',
       'Fish (appolo) - Retail', 'Cotton - Retail',
       'Cassava meal (attieke) - Retail', 'Cocoa - Retail',
       'Coffee - Retail', 'Rice (basmati, broken) - Wholesale',
       'Rice (Belem) - Wholesale', 'Beans (white) - Wholesale',
       'Rice (ordinary, first quality) - Retail',
       'Rice (ordinary, second quality) - Retail',
       'Rice (long grain) - Wholesale', 'Lentils - Wholesale',
       'Noodles (short) - Wholesale', 'Peanut - Wholesale',
       'Oil (vegetable, local) - Wholesale',
       'Tomatoes (greenhouse) - Wholesale', 'Lettuce - Wholesale',
       'Apples - Wholesale',
       'Rice (short grain, low quality, local) - Wholesale',
       'Cucumbers - Wholesale', 'Maize (white, dry) - Wholesale',
       'Avocados - Wholesale', 'Onions (white, dry) - Wholesale',
       'Pineapples - Wholesale', 'Peppers (fresh) - Wholesale',
       'Watermelons - Wholesale', 'Oat flakes - Wholesale',
       'Beans (pod) - Wholesale', 'Onions (red, dry) - Wholesale',
       'Potatoes (super chola) - Wholesale', 'Strawberries - Wholesale',
       'Melons (cantaloupe) - Wholesale',
       'Naranjilla (hybrid) - Wholesale',
       'Plantains (barraganete, mature) - Wholesale',
       'Plantains (barraganete, green) - Wholesale',
       'Plantains (dominico, mature) - Wholesale',
       'Plantains (dominico, green) - Wholesale',
       'Tree tomatoes - Wholesale', 'Grapes (black) - Wholesale',
       'Grapes (pink) - Wholesale', 'Oil (cooking) - Wholesale',
       'Beans (dry) - Wholesale', 'Wheat (imported) - Wholesale',
       'Beans (silk red) - Wholesale', 'Beans (silk red) - Retail',
       'Beans (fava) - Wholesale', 'Garlic - Retail',
       'Chickpeas - Wholesale', 'Wage (casual labour) - Retail',
       'Teff - Wholesale', 'Exchange rate (unofficial) - Retail',
       'Wheat (white) - Wholesale', 'Wheat (white) - Retail',
       'Teff (white) - Wholesale', 'Barley (white) - Wholesale',
       'Teff (red) - Wholesale', 'Lin seed - Wholesale',
       'Sorghum (mixed) - Wholesale', 'Niger seed - Wholesale',
       'Rape seed - Wholesale', 'Teff (Sergegna) - Wholesale',
       'Teff (Sergegna) - Retail', 'Peas (mixed) - Wholesale',
       'Barley - Retail', 'Livestock (Goat) - Retail',
       'Livestock (Sheep) - Retail', 'Teff (white) - Retail',
       'Teff (red) - Retail', 'Livestock (donkey) - Retail',
       'Livestock (camel) - Retail', 'Pasta (macaroni) - Retail',
       'Teff (mixed) - Retail', 'Butter (cow milk) - Retail',
       'Butter (goat milk) - Retail', 'Chickpeas - Retail',
       'Beans (fava, dry) - Retail', 'Beans (fava) - Retail',
       'Peas - Retail', 'Livestock (ox) - Retail', 'Meat - Retail',
       'Peppers (green) - Retail', 'Lettuce - Retail', 'Guava - Retail',
       'Mangoes - Retail', 'Kale - Retail', 'Swiss chard - Retail',
       'Beans (haricot, white) - Wholesale', 'Wheat (mixed) - Wholesale',
       'Wheat (mixed) - Retail', 'Barley (mixed) - Wholesale',
       'Beans (mung) - Retail', 'Millet (finger) - Retail',
       'Beans (haricot) - Retail', 'Niger seed - Retail',
       'Livestock (bull) - Retail', 'Honey - Retail',
       'Beans (haricot, red) - Wholesale',
       'Corn Soy Blend (CSB++, food aid) - Retail',
       'Wheat (food aid) - Retail', 'Kocho - Retail',
       'Maize (food aid) - Retail', 'Sorghum (food aid) - Retail',
       'Gari - Wholesale', 'Gari - Retail', 'Eggs - Wholesale',
       'Plantains (apentu) - Wholesale', 'Plantains (apentu) - Retail',
       'Cowpeas - Retail', 'Tomatoes (local) - Retail',
       'Cowpeas (white) - Wholesale', 'Plantains (apem) - Wholesale',
       'Plantains (apem) - Retail', 'Tomatoes (navrongo) - Wholesale',
       'Tomatoes (navrongo) - Retail', 'Peppers (fresh) - Retail',
       'Peppers (dried) - Wholesale', 'Peppers (dried) - Retail',
       'Yam (puna) - Wholesale', 'Yam (puna) - Retail',
       'Fish (mackerel, fresh) - Wholesale',
       'Fish (mackerel, fresh) - Retail',
       'Meat (chicken, local) - Wholesale', 'Tortilla (maize) - Retail',
       'Meat (beef, chops with bones) - Wholesale',
       'Cheese (dry) - Wholesale', 'Fonio - Retail',
       'Onions (imported) - Retail', 'Chili (red, dry raw) - Retail',
       'Beans (niebe, white) - Retail', 'Onions (local) - Retail',
       'Meat (beef, second quality) - Retail',
       'Fuel (Super Petrol) - Retail', 'Groundnuts (paste) - Retail',
       'Cucumbers - Retail', 'Meat (chicken, frozen, imported) - Retail',
       'Meat (sheep) - Retail', 'Meat (beef, without bones) - Retail',
       'Handwash soap - Retail', 'Fish (goldstripe sardinella) - Retail',
       'Bananas (local) - Retail', 'Meat (chicken, local) - Retail',
       'Fish (barbel, sole) - Retail', 'Fish (mullet, catfish) - Retail',
       'Firewood - Retail', 'Candles (small)  - Retail',
       'Candles (big)  - Retail', 'Batteries (small) - Retail',
       'Batteries (big) - Retail',
       'Meat (sheep, second quality) - Retail', 'Cashew fruit - Retail',
       'Meat (pork, first quality) - Retail',
       'Meat (pork, second quality) - Retail',
       'Bananas (imported) - Retail', 'Rice (tchako) - Retail',
       'Maize meal (local) - Retail', 'Maize meal (imported) - Retail',
       'Maize flour (white) - Wholesale',
       'Meat (chicken, broiler) - Retail', 'Chili (red) - Retail',
       'Milk (condensed) - Retail', "Chili (bird's eye) - Retail",
       'Onions (shallot) - Retail', "Chili (bird's eye, green) - Retail",
       'Chili (red, curly) - Retail', 'Eggs (broiler) - Retail',
       'Garlic (medium) - Retail', 'Rice (medium quality) - Retail',
       'Sugar (local) - Retail', 'Sugar (premium) - Retail',
       'Oil (vegetable, bulk) - Retail',
       'Oil (vegetable, packaged) - Retail',
       'Onions (shallot, medium) - Retail',
       'Meat (beef, first quality) - Retail',
       'Chili (red, large) - Retail', "Chili (bird's eye, red) - Retail",
       'Bread (khoboz) - Retail', 'Bulgur - Retail', 'Dates - Retail',
       'Cheese (local) - Retail', 'Meat (lamb) - Retail',
       'Toothbrush - Retail', 'Sanitary pads - Retail',
       'Toothpaste - Retail', 'Shampoo - Retail',
       'Disinfecting solution - Retail',
       'Rice (glutinous, unmilled) - Retail', 'Radish - Retail',
       'Oil (olive) - Retail', 'Oranges (big size) - Retail',
       'Cheese (picon) - Retail', 'Fish (tuna, canned) - Retail',
       'Bread (pita) - Retail', 'Cheese (white, boiled) - Retail',
       'Spinach - Retail', 'Milk (pasteurized) - Retail',
       'Wheat flour (first grade) - Retail', 'Oil (sunflower) - Retail',
       'Beans - Wholesale', 'Potatoes (Irish) - Wholesale',
       'Beans (dry) - Retail', 'Cooking fat - Retail',
       'Milk (UHT) - Retail', 'Milk (cow, fresh) - Retail',
       'Milk (camel, fresh) - Retail', 'Onions (red) - Retail',
       'Milk (cow, pasteurized) - Retail',
       'Rice (imported, Egyptian) - Retail',
       'Meat (beef, canned) - Retail', 'Bulgur (brown) - Retail',
       'Meat (chicken, whole, frozen) - Retail',
       'Lentils (green) - Retail', 'Lentils (red) - Retail',
       'Lentils (brown) - Retail',
       'Fuel (petrol-gasoline, 95 octane) - Retail',
       'Maize meal - Retail', 'Bread (brown) - Retail',
       'Beans (sugar-red) - Retail', 'Wheat meal - Retail',
       'Rice (small grain, imported) - Retail',
       'Wage (non-qualified labour, agricultural) - Retail',
       'Cane juice (strong) - Retail', 'Bitterball - Retail',
       'Cane juice (light) - Retail', 'Chili (green) - Retail',
       'Tea (black) - Retail', 'Tea (green) - Retail',
       'Milk (powder, infant formula) - Retail', 'Diapers - Retail',
       'Dishwashing liquid - Retail', 'Couscous - Retail',
       'Rice (paddy) - Producer', 'Cassava (dry) - Retail',
       'Maize (crushed) - Retail', 'Pigeon peas - Retail',
       'Meat (mutton) - Retail', 'Potatoes (red) - Retail',
       'Cassava leaves - Retail',
       'Livestock (sheep, medium-sized male) - Retail',
       'Livestock (goat, medium-sized male) - Retail',
       'Semolina - Retail',
       'Wage (non-qualified labour, livestock) - Retail',
       'Potato Leaves - Retail', 'Maize (local) - Retail',
       'Sorghum (taghalit) - Retail', 'Feed (flour) - Retail',
       'Feed (wheat bran) - Retail', 'Feed (rakhel) - Retail',
       'Straw - Retail', "Sorghum (r'haya) - Retail", 'Tortilla - Retail',
       'Beans (black, Veracruz) - Wholesale',
       'Beans (black, Zacatecas) - Wholesale',
       'Rice (long grain, Sinaloa) - Wholesale',
       'Rice (small grain, Morelos) - Wholesale',
       'Beans (black, Nayarit) - Wholesale',
       'Wheat flour (local) - Retail',
       'Maize meal (white, first grade) - Retail',
       'Oil (vegetable, local) - Retail',
       'Sugar (brown, imported) - Retail',
       'Sugar (brown, local) - Retail',
       'Maize meal (white, with bran) - Retail',
       'Garlic (large) - Retail', 'Garlic (small) - Retail',
       'Potatoes (Irish, imported) - Retail',
       'Potatoes (Irish, local) - Retail', 'Groundnuts (Mix) - Retail',
       'Beans (butter) - Retail', 'Beans (magnum) - Retail',
       'Groundnuts (large, shelled) - Retail',
       'Beans (catarino) - Retail',
       'Maize meal (white, without bran) - Retail',
       'Groundnuts (small, shelled) - Retail', 'Beans (fresh) - Retail',
       'Maize (imported) - Retail', 'Potatoes (unica) - Retail',
       'Chickpeas (local) - Retail', 'Oil (mixed, imported) - Retail',

In [44]:
# select only Thailand cause we will focusing only Thailand
thai_food_inflation = food_inflation[food_inflation['country'] == 'Thailand']

In [ ]:
thai_food_inflation

,country,product,price,month,year,unit,inflation_rate
1396300,Thailand,Maize - Wholesale,5.280,1,2000,KG,1.591969
1396301,Thailand,Maize - Wholesale,4.718,2,2000,KG,1.591969
1396302,Thailand,Maize - Wholesale,5.430,3,2000,KG,1.591969
1396303,Thailand,Maize - Wholesale,5.460,4,2000,KG,1.591969
1396304,Thailand,Maize - Wholesale,5.125,5,2000,KG,1.591969
...,...,...,...,...,...,...,...
1397144,Thailand,Meat (chicken) - Wholesale,47.470,11,2019,KG,0.706729
1397145,Thailand,Meat (chicken) - Wholesale,49.860,12,2019,KG,0.706729
1397146,Thailand,Meat (chicken) - Wholesale,48.730,1,2020,KG,-0.845937
1397147,Thailand,Meat (chicken) - Wholesale,46.000,2,2020,KG,-0.845937
1397148,Thailand,Meat (chicken) - Wholesale,45.500,3,2020,KG,-0.845937

In [54]:
thai_food_inflation['product'].unique()

array(['Maize - Wholesale', 'Rice - Wholesale',
       'Cassava flour - Wholesale', 'Meat (chicken) - Wholesale'],
      dtype=object)

In [47]:
# save as a csv file
thai_food_inflation.to_csv("../data/cleaned_data/thai_food_inflation.csv", index=False)